from parsimonious.grammar import Grammar

# ChamberTemperature = "M141"

grammar = Grammar(
    r"""
Document = Timestamp Thumbnail+
Thumbnail = BlankLine+ Header Payload+ Footer

BlankLine = ~r"[ \t\r]*\n"i
Timestamp = "; generated by " ~r"[^\n]+"i newline

Header = ";\n; thumbnail begin " Integer "x" Integer " " Integer newline
Payload = Colon ~r"[^\n ]+"i newline
Footer = "; thumbnail end\n;\n"

Comment = ~r";[^\n]*\n"
Command = ~r"[GM]\d+[^\n]*\n"

Integer = ~r"[1-9]\d*"i
Colon = "; "
newline = "\n"
"""
)
