from parsimonious.grammar import Grammar

# ChamberTemperature = "M141"

SYNTAX = r"""
Thumbnail = Header Payload+ Footer

BlankLine = ~r"[ \t\r]*\n"i
Timestamp = "; generated by " ~r"[^\n]+"i newline

Header = ";\n; thumbnail begin " Integer "x" Integer " " Integer newline
Payload = Colon ~r"[^\n ]+"i newline
Footer = "; thumbnail end\n;\n"

Comment = ~r";[^\n]*\n"
Command = ~r"[GM]\d+[^\n]*\n"

Integer = ~r"[1-9]\d*"i
Colon = "; "
newline = "\n"
"""

grammar = Grammar(
    "Document = Timestamp BlankLine+ Thumbnail "
    "(BlankLine+ Thumbnail)* (Command / Comment / BlankLine)*\n" + SYNTAX
)
