from parsimonious.grammar import Grammar

# ChamberTemperature = "M141"

grammar = Grammar(
    r"""
Document = (Timestamp / HeaderBlock) Thumbnail+
Thumbnail = Header Payload+ Footer

BlankLine = ~r"[ \t\r]*\n"i
Timestamp = "; generated by " ~r"[^\n]+" newline+

HeaderBlock = HeaderBeginTag (!HeaderEndTag Comment)+ HeaderEndTag newline+
HeaderBeginTag = "; HEADER_BLOCK_START\n"
HeaderEndTag = "; HEADER_BLOCK_END\n"

Header = ORCA_TAG? ";\n; thumbnail begin " Integer "x" Integer " " Integer newline
Payload = Colon ~r"[^\n ]+"i newline
Footer = "; thumbnail end\n" (ORCA_TAG / (BlankComment newline*))

Comment = ~r";[^\n]*\n"
Command = ~r"[GM]\d+[^\n]*\n"

ORCA_TAG = "; THUMBNAIL_BLOCK_" ("START" / "END") newline*
BlankComment = ";\n"

Integer = ~r"[1-9]\d*"i
Colon = "; "
newline = "\n"
"""
)
