from parsimonious.grammar import Grammar

# ChamberTemperature = "M141"

grammar = Grammar(
    r"""
Document = Timestamp Thumbnail+
Thumbnail = BlankLine+ Header Payload+ Footer

BlankLine = ~r"[ \t\r]*\n"i
Timestamp = "; generated by " ~r"[^\n]+"i newline

Header = ORCA_TAG? ";\n; thumbnail begin " Integer "x" Integer " " Integer newline
Payload = Colon ~r"[^\n ]+"i newline
Footer = "; thumbnail end\n" (ORCA_TAG / BlankComment)

Comment = ~r";[^\n]*\n"
Command = ~r"[GM]\d+[^\n]*\n"

ORCA_TAG = ~r"; THUMBNAIL_BLOCK_[^\n]+" newline+
BlankComment = ";\n"

Integer = ~r"[1-9]\d*"i
Colon = "; "
newline = "\n"
"""
)
