# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python tests

on:
  push:
    branches: [ experimental ]
  pull_request:
    types: [edited, submitted]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip

    # UV is the pip accelerator.
    - name: Install dependencies
      run: |
        sudo apt-get install build-essential
        pip install --upgrade uv
        uv pip install --system .[test]

    - name: Lint with Ruff
      run: ruff check mbotmake2/

    - name: Lint with mypy
      run: mypy --ignore-missing-imports mbotmake2

    - name: Test with pytest
      run: pytest tests/

    - name: Run build script
      run: uv build